services:
  - type: web
    name: pet-adoption-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run dev
    envVars:
      - key: NODE_VERSION
        value: 18.20.2
    autoDeploy: true
    rootDir: pet-adoption-backend
  - type: static
    name: pet-marketplace-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    rootDir: pet-marketplace-frontend
